name: GlobalFlowRecon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.9
  - tensorflow-gpu=1.12.0
  - numpy=1.17.2
  - scipy=1.3.1
  - matplotlib=3.1.1
  - imageio=2.6.0
  - contextlib2=0.6.0
  - munch=2.5.0