#pragma once

#ifndef _INCLUDE_BLENDINGSETTINGS
#define _INCLUDE_BLENDINGSETTINGS
namespace Blending{
enum BlendMode{
	BLEND_BEERLAMBERT,
	BLEND_BEERLAMBERT_EXCLUSIVE,
	BLEND_ALPHA,
	BLEND_ALPHAADDITIVE,
	BLEND_ADDITIVE,
};
}

#endif //_INCLUDE_BLENDINGSETTINGS